version: "3"
services:
  app:
    build: ./
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mariadb:10.7
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_USER=admin
      - MYSQL_DATABASE=skripsi_silvi

  phpmyadmin:
    image: phpmyadmin
    restart: always
    expose:
      - "8008"
    ports:
      - "8008:8008"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
